### ISSUE TITLE
BadDeviceToken error with correct device token

### ISSUE THREAD

**Issue by pfurtek** [alexeyxo/swift-apns#3]
Hello!

I'm trying to use your example code for my application. I'm getting the device token correctly from the app, but no matter what I do I always get the BadDeviceToken error.

Do you know why would that happen? The app I'm trying to send it to is in Enterprise distribution, and I'm using the certificate downloaded from apple member center for distribution.

Could you also explain to me what should go as the "topic"? Bundle id of the sending app or the receiving app?

Any help and ideas would be greatly appreciated!

Thank you!

**Comment by sergiobuonanno** [comment]
I have the same problem. I don't understand why the post was closed without answer
