### ISSUE TITLE
Fatal error in sendPush

### ISSUE THREAD

**Issue by didier-v** [alexeyxo/swift-apns#4]
The error happens  in the completion handler of the task:
in APNSNetwork.swift -> sendPush

```
 let task = self.session?.dataTaskWithRequest(request, completionHandler: { (data, response, err) -> Void in
let (statusCode, status) = APNServiceStatus.checkStatusCode((response as! NSHTTPURLResponse)) 
```

I got an error (err = Error Domain=NSURLErrorDomain Code=-1001 "The request timed out.") and response is nil
Force unwrap of response causes a fatal error.

**Comment by alexeyxo** [comment]
Bug is fixed in swift3.0 branch.
