### ISSUE TITLE
Not working .. at least with iOS 10 and swift 3.0

### ISSUE THREAD

**Issue by sergiobuonanno** [alexeyxo/swift-apns#6]
I only succeeded to get statusCode 403, translated from your library in "Bad Certificate" (not exactly the same meaning of the HTTP status code 403). My certificate is 100% genuine p12 certificate, working, for example, with NWPusher (another iOS library you can find on GitHub) and from other server endpoints. I would have liked to use your library because NWPusher is still written in legacy Obj-C code...but unfortunately I couldn't manage to make it work... have you any hint ? Have you tried to send a push notification to another iOS device ?... sorry for the stupid question but your examples do not work even with a basic test application in Xcode 8.0 (by just copying and pasting your code it didn't work for me).

**Comment by adirburke** [comment]
I had the same problems 
![capture](https://cloud.githubusercontent.com/assets/8197402/21740967/a0c82c94-d51d-11e6-92fa-7be2867c7a29.JPG)
